"""empty message

Revision ID: cde7c08b6395
Revises: 34c2c9941298
Create Date: 2025-01-07 21:06:59.528465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cde7c08b6395'
down_revision: Union[str, None] = '34c2c9941298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_tickets_id', table_name='tickets')
    op.drop_table('tickets')
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    op.drop_column('users', 'deleted')
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='ticketstatus'), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='tickets_booking_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tickets_pkey')
    )
    op.create_index('ix_tickets_id', 'tickets', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('space_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='bookingstatus'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name='bookings_customer_id_fkey'),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lot.id'], name='bookings_lot_id_fkey'),
    sa.ForeignKeyConstraint(['space_id'], ['parking_space.space_id'], name='bookings_space_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bookings_pkey')
    )
    op.create_index('ix_bookings_id', 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###
